### ISSUE TITLE
React scan breaks with react-three-fiber

### ISSUE THREAD

**Issue by darklight9811** [aidenybai/react-scan#175]
I'm currently using react-three-fiber and it starts throwing the following error when the canvas render:

```
TypeError: IntersectionObserver.observe: Argument 1 does not implement interface Element.
```

![image](https://github.com/user-attachments/assets/9ae676d8-e878-4248-b4cd-75f2a784413e)

Those only occur in pages with react-three-fiber

**Comment by lxsmnsyc** [comment]
should be fixed in #172

**Comment by darklight9811** [comment]
@lxsmnsyc is this live? I just tested with the most recent version I could get on npm and the error still persisted

**Comment by lxsmnsyc** [comment]
@darklight9811 I don't think it's released yet. I'll follow up

**Comment by RobPruzan** [comment]
Fixed on react-scan@0.1.0
