### ISSUE TITLE
Extension causes an error with react devtool.

### ISSUE THREAD

**Issue by ramifara** [aidenybai/react-scan#324]
I have installed the extension after following the instruction and as soon as I activate it, this error from react dev tool appears. this error does not happen when I deactivate the react-scan extension. 

![Image](https://github.com/user-attachments/assets/b974eaef-77f5-4521-885c-bfd99947eed0)

Locally it blocks the page, but its possible to close the error overlay and then it is possible to use the app and extension functions as expected. in the deployed version there is only an error on the console. 

This issue exists on any react/nextjs page that i visited. 

![Image](https://github.com/user-attachments/assets/77cffa66-ce7b-46c4-8f2b-d04535781df9)

**Comment by ramifara** [comment]
Hi @pivanov  Thank you for looking into it, unfortunately after installing the new version I still get the same error with the extension, which still seems like having some conflict with React Dev Tool extension, I am not sure if its something on my side or not but I have tested it on multiple chrome instances. only on incognito where I dont have react dev tool this issue does not happen.

the errors are: 

`Uncaught TypeError: window.__REACT_DEVTOOLS_GLOBAL_HOOK__.on is not a function
    at installHook.js:52:41
    at installHook.js:1:151562
    at installHook.js:1:151566`

and 
`Uncaught TypeError: Cannot read properties of undefined (reading 'has')
    at registerRenderer (backendManager.js:1:24203)
    at backendManager.js:1:25822
    at Map.forEach (<anonymous>)
    at backendManager.js:1:25809
    at welcome (backendManager.js:1:26160)`


let me know if I can provide any other information

**Comment by ramifara** [comment]
I have deactivated react dev tool for now and the error is gone, but for the time being I need to switch between them. :)

**Comment by ArsenicBismuth** [comment]
Still got this issue with v1.0.9

![Image](https://github.com/user-attachments/assets/950686c4-7038-436d-a77d-cd4599493560)

**Comment by dimashpt** [comment]
Same here using v1.0.9 from chrome webstore

**Comment by RobPruzan** [comment]
I believe this is fixed in extension version 1.0.10, which has not been published to the chrome web store. It's available directly through the repo, instructions here- https://github.com/aidenybai/react-scan/blob/main/BROWSER_EXTENSION_GUIDE.md

Waiting on my verification from chrome web store to be able to publish latest

**Comment by RobPruzan** [comment]
I believe this is fixed, and haven't seen any activity here showing otherwise, so going to close the issue

**Comment by h3adache** [comment]
Just FYI the chrome store still shows version 1.0.9. I see the version here is already on 1.1.4 but that version still causes errors:

```installHook.js:52 Uncaught TypeError: window.__REACT_DEVTOOLS_GLOBAL_HOOK__.on is not a function
    at installHook.js:1:146165
    at installHook.js:1:146169
```

**Comment by MhL5** [comment]
> Just FYI the chrome store still shows version 1.0.9. I see the version here is already on 1.1.4 but that version still causes errors:
> 
> ```
>     at installHook.js:1:146165
>     at installHook.js:1:146169
> ```

same experience, the chrome version  is 1.0.9 and it throws error constantly

**Comment by jasekiw** [comment]
@RobPruzan I just installed the extension from the chrome web store and ran into this issue today. The chrome web store is outdated, this needs attention.

**Comment by mateosayas** [comment]
@RobPruzan I Installed the extension on Chrome (thought web store) a few minutes ago and got the same error. Would be amazing if this could be looked at 🙌🏻

**Comment by hungtk** [comment]
I installed the extension both manually and Chrome store then got the same error. Please take a look.

<img width="1710" height="902" alt="Image" src="https://github.com/user-attachments/assets/ef2adc2c-d7a1-4df0-9472-ff25b584595b" />

**Comment by theArina** [comment]
Currently Chrome extension from the Web Store has version 1.0.9 and the issue persist. 
The updated v1.1.4 from manual installation does not have the issue.
