### ISSUE TITLE
Crahes when target page immediately triggers a redirect

### ISSUE THREAD

**Issue by levrik** [aidenybai/react-scan#40]
Executing `npx react-scan@latest` against an URL which immediately triggers a redirect through JS crashes with the following error:

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.addScriptTag: Execution context was destroyed, most likely because of a navigation
    at /Users/levrik/.npm/_npx/bfc758176cdd0246/node_modules/react-scan/dist/cli.js:1:4086 {
  name: 'Error'
}
```

Sadly I cannot share the URL as it's internal and I couldn't find a public page which has the same issue.

**Comment by aidenybai** [comment]
@levrik fixed in latest

**Comment by levrik** [comment]
@aidenybai The issue still reproduces for me on `react-scan@0.0.34`.

**Comment by aidenybai** [comment]
Closing — this was addressed in a previous release. Please open a new issue if it still reproduces.
